
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

#MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/coursedb
spring.datasource.username=root
spring.datasource.password=root

#JPA

spring.jpa.hibernate.ddl-auto=update 
# Hibernate compares java entity with database, if there is any mismatch, it correct it in db. eg. if new object added into entity, new column will be created into its corresponding table.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




#TheamLeaf

spring.thymeleaf.cache=false